// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjvwyuzwqmggmrhdazux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qdnd5dXp3cW1nZ21yaGRhenV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0Mjc5ODEsImV4cCI6MjA1NTAwMzk4MX0.13eo3E5uSgtAeECoxe77BZC7qvRoVa3AY45CuuufbDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);